#!/bin/bash
#PBS -l procs=4,walltime=10:00
#PBS -N bfs_job
#PBS -q edu_shared

#PBS -e output/mpitest_168_4_Exp.err
#PBS -o output/mpitest_168_4_Exp.out
#PBS -d ./

module load tools/mpich2-1.5-gcc

mpirun -machinefile $PBS_NODEFILE -np 4 ./bin/bfs 168 Exp
