#!/bin/bash
#PBS -l nodes=1:ppn=16,walltime=1:00 
#PBS -N hctestJob
#PBS -q edu_shared

#PBS -e /export/home/agualc2/ece566_hw/hw1/hypercube/pbs_files/only_N/n1_ppn16_k16/mpitest_16384.err
#PBS -o /export/home/agualc2/ece566_hw/hw1/hypercube/pbs_files/only_N/n1_ppn16_k16/mpitest_16384.out
#PBS -d /export/home/agualc2/ece566_hw/hw1/hypercube

module load tools/mpich2-1.5-gcc

mpirun -machinefile $PBS_NODEFILE -np 16 /export/home/agualc2/ece566_hw/hw1/hypercube/hctest 16384 
