#!/bin/bash
#PBS -l nodes=1:ppn=16,walltime=10:00 
#PBS -N hctestJob
#PBS -q edu_shared

#PBS -e /export/home/acipol2/ece566_hw/hw1/hypercube/pbs_files/only_N/mpitest_16.err
#PBS -o /export/home/acipol2/ece566_hw/hw1/hypercube/pbs_files/only_N/mpitest_16.out
#PBS -d /export/home/acipol2/ece566_hw/hw1/hypercube

module load tools/mpich2-1.5-gcc

mpirun -machinefile $PBS_NODEFILE -np 16 /export/home/acipol2/ece566_hw/hw1/hypercube/hctest 67108864 
