#!/bin/bash
#PBS -l nodes=4:ppn=4,walltime=13:00 
#PBS -N ringtestJob
#PBS -q edu_shared

#PBS -e /export/home/acipol2/ece566_hw/hw1/ring/pbs_files/only_N/n4_ppn4_k16/mpitest_4194304.err
#PBS -o /export/home/acipol2/ece566_hw/hw1/ring/pbs_files/only_N/n4_ppn4_k16/mpitest_4194304.out
#PBS -d /export/home/acipol2/ece566_hw/hw1/ring

module load tools/mpich2-1.5-gcc

mpirun -machinefile $PBS_NODEFILE -np 16 /export/home/acipol2/ece566_hw/hw1/ring/ringtest 4194304 
