#!/bin/bash
#PBS -l nodes=4:ppn=4,walltime=1:00 
#PBS -N hctestJob
#PBS -q edu_shared

#PBS -e /export/home/agualc2/ece566_hw/hw1/hypercube/pbs_files/only_N/n4_ppn4_k16/mpitest_4096.err
#PBS -o /export/home/agualc2/ece566_hw/hw1/hypercube/pbs_files/only_N/n4_ppn4_k16/mpitest_4096.out
#PBS -d /export/home/agualc2/ece566_hw/hw1/hypercube

module load tools/mpich2-1.5-gcc

mpirun -machinefile $PBS_NODEFILE -np 16 /export/home/acipol2/ece566_hw/hw1/hypercube/hctest 4096
